/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 59
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 1
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_input = 1,
  anon_sym_filter = 2,
  anon_sym_output = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  sym_plugin_name = 6,
  anon_sym_EQ_GT = 7,
  sym_whitespace = 8,
  anon_sym_POUND = 9,
  aux_sym_comment_token1 = 10,
  sym_newline = 11,
  sym_string = 12,
  sym_number = 13,
  anon_sym_true = 14,
  anon_sym_false = 15,
  anon_sym_LBRACK = 16,
  anon_sym_COMMA = 17,
  anon_sym_RBRACK = 18,
  sym_source_file = 19,
  sym_pipeline = 20,
  sym_input_section = 21,
  sym_filter_section = 22,
  sym_output_section = 23,
  sym_block = 24,
  sym_block_content = 25,
  sym_expression = 26,
  sym_expression_key = 27,
  sym_expression_value = 28,
  sym_comment = 29,
  sym_boolean = 30,
  sym_array = 31,
  aux_sym_source_file_repeat1 = 32,
  aux_sym_input_section_repeat1 = 33,
  aux_sym_block_repeat1 = 34,
  aux_sym_array_repeat1 = 35,
  anon_alias_sym_identifier = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_input] = "input",
  [anon_sym_filter] = "filter",
  [anon_sym_output] = "output",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_plugin_name] = "plugin_name",
  [anon_sym_EQ_GT] = "=>",
  [sym_whitespace] = "whitespace",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_newline] = "newline",
  [sym_string] = "string",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym_pipeline] = "pipeline",
  [sym_input_section] = "input_section",
  [sym_filter_section] = "filter_section",
  [sym_output_section] = "output_section",
  [sym_block] = "block",
  [sym_block_content] = "block_content",
  [sym_expression] = "expression",
  [sym_expression_key] = "expression_key",
  [sym_expression_value] = "expression_value",
  [sym_comment] = "comment",
  [sym_boolean] = "boolean",
  [sym_array] = "array",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_input_section_repeat1] = "input_section_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [anon_alias_sym_identifier] = "identifier",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_input] = anon_sym_input,
  [anon_sym_filter] = anon_sym_filter,
  [anon_sym_output] = anon_sym_output,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_plugin_name] = sym_plugin_name,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [sym_whitespace] = sym_whitespace,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_newline] = sym_newline,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym_pipeline] = sym_pipeline,
  [sym_input_section] = sym_input_section,
  [sym_filter_section] = sym_filter_section,
  [sym_output_section] = sym_output_section,
  [sym_block] = sym_block,
  [sym_block_content] = sym_block_content,
  [sym_expression] = sym_expression,
  [sym_expression_key] = sym_expression_key,
  [sym_expression_value] = sym_expression_value,
  [sym_comment] = sym_comment,
  [sym_boolean] = sym_boolean,
  [sym_array] = sym_array,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_input_section_repeat1] = aux_sym_input_section_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [anon_alias_sym_identifier] = anon_alias_sym_identifier,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_input] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_filter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_output] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_plugin_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_whitespace] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_pipeline] = {
    .visible = true,
    .named = true,
  },
  [sym_input_section] = {
    .visible = true,
    .named = true,
  },
  [sym_filter_section] = {
    .visible = true,
    .named = true,
  },
  [sym_output_section] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block_content] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_key] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_value] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_input_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_identifier] = {
    .visible = true,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = anon_alias_sym_identifier,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 3,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 13,
  [16] = 8,
  [17] = 9,
  [18] = 11,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 27,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 28,
  [43] = 26,
  [44] = 19,
  [45] = 36,
  [46] = 46,
  [47] = 34,
  [48] = 48,
  [49] = 35,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '\n', 57,
        '"', 3,
        '#', 58,
        ',', 68,
        '=', 4,
        '[', 67,
        ']', 69,
        'f', 32,
        'i', 40,
        'o', 50,
        't', 44,
        '{', 30,
        '}', 31,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 57,
        '"', 3,
        '#', 58,
        ',', 68,
        '[', 67,
        ']', 69,
        'f', 33,
        't', 44,
        '{', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '#') ADVANCE(58);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(62);
      if (lookahead == '\\') ADVANCE(20);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(55);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 6:
      if (lookahead == 'i') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'p') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(5);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 18:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 20:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 21:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '#') ADVANCE(58);
      if (lookahead == 'f') ADVANCE(6);
      if (lookahead == 'i') ADVANCE(8);
      if (lookahead == 'o') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      END_STATE();
    case 22:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '#') ADVANCE(58);
      if (lookahead == 'f') ADVANCE(37);
      if (lookahead == 'i') ADVANCE(40);
      if (lookahead == 'o') ADVANCE(50);
      if (lookahead == '{') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_input);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_input);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_filter);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_filter);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_output);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_output);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'a') ADVANCE(38);
      if (lookahead == 'i') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'a') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'e') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'e') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'e') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'i') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'l') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'l') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'n') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'p') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'p') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'r') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'r') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 's') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 't') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 't') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 't') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 't') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'u') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'u') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'u') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'u') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_plugin_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_whitespace);
      if (lookahead == '\n') ADVANCE(57);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_whitespace);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(61);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead == '#') ADVANCE(59);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 21},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 21},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 21},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 22},
  [21] = {.lex_state = 22},
  [22] = {.lex_state = 22},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 22},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 22},
  [30] = {.lex_state = 22},
  [31] = {.lex_state = 22},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 22},
  [34] = {.lex_state = 22},
  [35] = {.lex_state = 22},
  [36] = {.lex_state = 22},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 21},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 21},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 60},
  [57] = {.lex_state = 0},
  [58] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_input] = ACTIONS(1),
    [anon_sym_filter] = ACTIONS(1),
    [anon_sym_output] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_plugin_name] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [sym_whitespace] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(5),
    [sym_newline] = ACTIONS(7),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(55),
    [sym_pipeline] = STATE(51),
    [sym_input_section] = STATE(41),
    [sym_filter_section] = STATE(41),
    [sym_output_section] = STATE(41),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_input] = ACTIONS(11),
    [anon_sym_filter] = ACTIONS(13),
    [anon_sym_output] = ACTIONS(15),
    [sym_whitespace] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(5),
    [sym_newline] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      sym_plugin_name,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(2), 1,
      sym_comment,
    STATE(38), 1,
      sym_block,
    STATE(40), 1,
      sym_expression_value,
    ACTIONS(21), 2,
      sym_string,
      sym_number,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_boolean,
      sym_array,
  [40] = 12,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(27), 1,
      sym_plugin_name,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_RBRACK,
    STATE(3), 1,
      sym_comment,
    STATE(4), 1,
      aux_sym_array_repeat1,
    STATE(24), 1,
      sym_expression_value,
    ACTIONS(29), 2,
      sym_string,
      sym_number,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 2,
      sym_boolean,
      sym_array,
  [80] = 11,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(37), 1,
      sym_plugin_name,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_RBRACK,
    STATE(24), 1,
      sym_expression_value,
    ACTIONS(40), 2,
      sym_string,
      sym_number,
    ACTIONS(43), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_comment,
      aux_sym_array_repeat1,
    STATE(26), 2,
      sym_boolean,
      sym_array,
  [118] = 12,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(27), 1,
      sym_plugin_name,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(51), 1,
      anon_sym_RBRACK,
    STATE(4), 1,
      aux_sym_array_repeat1,
    STATE(5), 1,
      sym_comment,
    STATE(24), 1,
      sym_expression_value,
    ACTIONS(29), 2,
      sym_string,
      sym_number,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 2,
      sym_boolean,
      sym_array,
  [158] = 12,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(27), 1,
      sym_plugin_name,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(53), 1,
      anon_sym_RBRACK,
    STATE(5), 1,
      aux_sym_array_repeat1,
    STATE(6), 1,
      sym_comment,
    STATE(24), 1,
      sym_expression_value,
    ACTIONS(29), 2,
      sym_string,
      sym_number,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 2,
      sym_boolean,
      sym_array,
  [198] = 12,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(27), 1,
      sym_plugin_name,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 1,
      anon_sym_RBRACK,
    STATE(3), 1,
      aux_sym_array_repeat1,
    STATE(7), 1,
      sym_comment,
    STATE(24), 1,
      sym_expression_value,
    ACTIONS(29), 2,
      sym_string,
      sym_number,
    ACTIONS(31), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(26), 2,
      sym_boolean,
      sym_array,
  [238] = 13,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      anon_sym_RBRACE,
    ACTIONS(59), 1,
      sym_plugin_name,
    ACTIONS(61), 1,
      sym_string,
    STATE(8), 1,
      sym_comment,
    STATE(12), 1,
      aux_sym_block_repeat1,
    STATE(39), 1,
      sym_block,
    STATE(46), 1,
      sym_expression,
    STATE(48), 1,
      sym_block_content,
    STATE(54), 1,
      sym_expression_key,
  [278] = 13,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(57), 1,
      anon_sym_RBRACE,
    ACTIONS(59), 1,
      sym_plugin_name,
    ACTIONS(61), 1,
      sym_string,
    STATE(9), 1,
      sym_comment,
    STATE(11), 1,
      aux_sym_block_repeat1,
    STATE(39), 1,
      sym_block,
    STATE(46), 1,
      sym_expression,
    STATE(48), 1,
      sym_block_content,
    STATE(54), 1,
      sym_expression_key,
  [318] = 10,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 1,
      anon_sym_input,
    ACTIONS(68), 1,
      anon_sym_filter,
    ACTIONS(71), 1,
      anon_sym_output,
    STATE(51), 1,
      sym_pipeline,
    STATE(10), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(41), 3,
      sym_input_section,
      sym_filter_section,
      sym_output_section,
  [352] = 13,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      sym_plugin_name,
    ACTIONS(61), 1,
      sym_string,
    ACTIONS(74), 1,
      anon_sym_RBRACE,
    STATE(11), 1,
      sym_comment,
    STATE(12), 1,
      aux_sym_block_repeat1,
    STATE(39), 1,
      sym_block,
    STATE(46), 1,
      sym_expression,
    STATE(48), 1,
      sym_block_content,
    STATE(54), 1,
      sym_expression_key,
  [392] = 12,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(76), 1,
      anon_sym_LBRACE,
    ACTIONS(79), 1,
      anon_sym_RBRACE,
    ACTIONS(81), 1,
      sym_plugin_name,
    ACTIONS(84), 1,
      sym_string,
    STATE(39), 1,
      sym_block,
    STATE(46), 1,
      sym_expression,
    STATE(48), 1,
      sym_block_content,
    STATE(54), 1,
      sym_expression_key,
    STATE(12), 2,
      sym_comment,
      aux_sym_block_repeat1,
  [430] = 13,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      sym_plugin_name,
    ACTIONS(61), 1,
      sym_string,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      aux_sym_block_repeat1,
    STATE(13), 1,
      sym_comment,
    STATE(39), 1,
      sym_block,
    STATE(46), 1,
      sym_expression,
    STATE(48), 1,
      sym_block_content,
    STATE(54), 1,
      sym_expression_key,
  [470] = 11,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(11), 1,
      anon_sym_input,
    ACTIONS(13), 1,
      anon_sym_filter,
    ACTIONS(15), 1,
      anon_sym_output,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      aux_sym_source_file_repeat1,
    STATE(14), 1,
      sym_comment,
    STATE(51), 1,
      sym_pipeline,
    STATE(41), 3,
      sym_input_section,
      sym_filter_section,
      sym_output_section,
  [506] = 13,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      sym_plugin_name,
    ACTIONS(61), 1,
      sym_string,
    ACTIONS(91), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      sym_comment,
    STATE(16), 1,
      aux_sym_block_repeat1,
    STATE(39), 1,
      sym_block,
    STATE(46), 1,
      sym_expression,
    STATE(48), 1,
      sym_block_content,
    STATE(54), 1,
      sym_expression_key,
  [546] = 13,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      sym_plugin_name,
    ACTIONS(61), 1,
      sym_string,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      aux_sym_block_repeat1,
    STATE(16), 1,
      sym_comment,
    STATE(39), 1,
      sym_block,
    STATE(46), 1,
      sym_expression,
    STATE(48), 1,
      sym_block_content,
    STATE(54), 1,
      sym_expression_key,
  [586] = 13,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      sym_plugin_name,
    ACTIONS(61), 1,
      sym_string,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    STATE(17), 1,
      sym_comment,
    STATE(18), 1,
      aux_sym_block_repeat1,
    STATE(39), 1,
      sym_block,
    STATE(46), 1,
      sym_expression,
    STATE(48), 1,
      sym_block_content,
    STATE(54), 1,
      sym_expression_key,
  [626] = 13,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(17), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      sym_plugin_name,
    ACTIONS(61), 1,
      sym_string,
    ACTIONS(95), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      aux_sym_block_repeat1,
    STATE(18), 1,
      sym_comment,
    STATE(39), 1,
      sym_block,
    STATE(46), 1,
      sym_expression,
    STATE(48), 1,
      sym_block_content,
    STATE(54), 1,
      sym_expression_key,
  [666] = 6,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(19), 1,
      sym_comment,
    ACTIONS(97), 3,
      sym_plugin_name,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(99), 5,
      sym_string,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [691] = 10,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(101), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      sym_plugin_name,
    STATE(20), 1,
      sym_comment,
    STATE(22), 1,
      aux_sym_input_section_repeat1,
    STATE(33), 1,
      sym_block,
    ACTIONS(103), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [724] = 10,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      sym_plugin_name,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      aux_sym_input_section_repeat1,
    STATE(21), 1,
      sym_comment,
    STATE(33), 1,
      sym_block,
    ACTIONS(111), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [757] = 9,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    ACTIONS(117), 1,
      anon_sym_LBRACE,
    ACTIONS(120), 1,
      sym_plugin_name,
    STATE(33), 1,
      sym_block,
    STATE(22), 2,
      sym_comment,
      aux_sym_input_section_repeat1,
    ACTIONS(115), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [788] = 6,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(23), 1,
      sym_comment,
    ACTIONS(123), 3,
      sym_plugin_name,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(125), 5,
      sym_string,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [813] = 7,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    STATE(24), 1,
      sym_comment,
    ACTIONS(127), 3,
      sym_plugin_name,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(129), 4,
      sym_string,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [840] = 10,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      sym_plugin_name,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
    STATE(22), 1,
      aux_sym_input_section_repeat1,
    STATE(25), 1,
      sym_comment,
    STATE(33), 1,
      sym_block,
    ACTIONS(135), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [873] = 6,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(26), 1,
      sym_comment,
    ACTIONS(137), 3,
      sym_plugin_name,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(139), 5,
      sym_string,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [898] = 6,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(27), 1,
      sym_comment,
    ACTIONS(141), 3,
      sym_plugin_name,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(143), 5,
      sym_string,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [923] = 6,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(28), 1,
      sym_comment,
    ACTIONS(145), 3,
      sym_plugin_name,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(147), 5,
      sym_string,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [948] = 10,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      sym_plugin_name,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      aux_sym_input_section_repeat1,
    STATE(29), 1,
      sym_comment,
    STATE(33), 1,
      sym_block,
    ACTIONS(151), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [981] = 10,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      sym_plugin_name,
    ACTIONS(153), 1,
      ts_builtin_sym_end,
    STATE(22), 1,
      aux_sym_input_section_repeat1,
    STATE(30), 1,
      sym_comment,
    STATE(33), 1,
      sym_block,
    ACTIONS(155), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [1014] = 10,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      sym_plugin_name,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      aux_sym_input_section_repeat1,
    STATE(31), 1,
      sym_comment,
    STATE(33), 1,
      sym_block,
    ACTIONS(159), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [1047] = 6,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(32), 1,
      sym_comment,
    ACTIONS(161), 3,
      sym_plugin_name,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(49), 4,
      sym_string,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1071] = 6,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(33), 1,
      sym_comment,
    ACTIONS(163), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(165), 4,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
      sym_plugin_name,
  [1094] = 6,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(34), 1,
      sym_comment,
    ACTIONS(167), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(169), 4,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
      sym_plugin_name,
  [1117] = 6,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(35), 1,
      sym_comment,
    ACTIONS(171), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(173), 4,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
      sym_plugin_name,
  [1140] = 6,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(36), 1,
      sym_comment,
    ACTIONS(175), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(177), 4,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
      sym_plugin_name,
  [1163] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(37), 1,
      sym_comment,
    ACTIONS(143), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_plugin_name,
      sym_string,
  [1182] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(38), 1,
      sym_comment,
    ACTIONS(179), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_plugin_name,
      sym_string,
  [1201] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(39), 1,
      sym_comment,
    ACTIONS(181), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_plugin_name,
      sym_string,
  [1220] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(40), 1,
      sym_comment,
    ACTIONS(179), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_plugin_name,
      sym_string,
  [1239] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(41), 1,
      sym_comment,
    ACTIONS(183), 4,
      ts_builtin_sym_end,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [1258] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(42), 1,
      sym_comment,
    ACTIONS(147), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_plugin_name,
      sym_string,
  [1277] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(43), 1,
      sym_comment,
    ACTIONS(139), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_plugin_name,
      sym_string,
  [1296] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(44), 1,
      sym_comment,
    ACTIONS(99), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_plugin_name,
      sym_string,
  [1315] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(45), 1,
      sym_comment,
    ACTIONS(175), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_plugin_name,
      sym_string,
  [1334] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(46), 1,
      sym_comment,
    ACTIONS(181), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_plugin_name,
      sym_string,
  [1353] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(47), 1,
      sym_comment,
    ACTIONS(167), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_plugin_name,
      sym_string,
  [1372] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(48), 1,
      sym_comment,
    ACTIONS(185), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_plugin_name,
      sym_string,
  [1391] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(49), 1,
      sym_comment,
    ACTIONS(171), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_plugin_name,
      sym_string,
  [1410] = 6,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(187), 1,
      anon_sym_LBRACE,
    STATE(50), 1,
      sym_comment,
    ACTIONS(125), 3,
      anon_sym_RBRACE,
      sym_plugin_name,
      sym_string,
  [1431] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    STATE(51), 1,
      sym_comment,
    ACTIONS(190), 4,
      ts_builtin_sym_end,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [1450] = 6,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(192), 1,
      anon_sym_LBRACE,
    ACTIONS(194), 1,
      anon_sym_EQ_GT,
    STATE(52), 1,
      sym_comment,
  [1469] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      sym_comment,
  [1485] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(198), 1,
      anon_sym_EQ_GT,
    STATE(54), 1,
      sym_comment,
  [1501] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(200), 1,
      ts_builtin_sym_end,
    STATE(55), 1,
      sym_comment,
  [1517] = 4,
    ACTIONS(202), 1,
      anon_sym_POUND,
    ACTIONS(204), 1,
      aux_sym_comment_token1,
    STATE(56), 1,
      sym_comment,
    ACTIONS(7), 2,
      sym_whitespace,
      sym_newline,
  [1531] = 5,
    ACTIONS(3), 1,
      sym_whitespace,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(206), 1,
      anon_sym_EQ_GT,
    STATE(57), 1,
      sym_comment,
  [1547] = 1,
    ACTIONS(208), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 118,
  [SMALL_STATE(6)] = 158,
  [SMALL_STATE(7)] = 198,
  [SMALL_STATE(8)] = 238,
  [SMALL_STATE(9)] = 278,
  [SMALL_STATE(10)] = 318,
  [SMALL_STATE(11)] = 352,
  [SMALL_STATE(12)] = 392,
  [SMALL_STATE(13)] = 430,
  [SMALL_STATE(14)] = 470,
  [SMALL_STATE(15)] = 506,
  [SMALL_STATE(16)] = 546,
  [SMALL_STATE(17)] = 586,
  [SMALL_STATE(18)] = 626,
  [SMALL_STATE(19)] = 666,
  [SMALL_STATE(20)] = 691,
  [SMALL_STATE(21)] = 724,
  [SMALL_STATE(22)] = 757,
  [SMALL_STATE(23)] = 788,
  [SMALL_STATE(24)] = 813,
  [SMALL_STATE(25)] = 840,
  [SMALL_STATE(26)] = 873,
  [SMALL_STATE(27)] = 898,
  [SMALL_STATE(28)] = 923,
  [SMALL_STATE(29)] = 948,
  [SMALL_STATE(30)] = 981,
  [SMALL_STATE(31)] = 1014,
  [SMALL_STATE(32)] = 1047,
  [SMALL_STATE(33)] = 1071,
  [SMALL_STATE(34)] = 1094,
  [SMALL_STATE(35)] = 1117,
  [SMALL_STATE(36)] = 1140,
  [SMALL_STATE(37)] = 1163,
  [SMALL_STATE(38)] = 1182,
  [SMALL_STATE(39)] = 1201,
  [SMALL_STATE(40)] = 1220,
  [SMALL_STATE(41)] = 1239,
  [SMALL_STATE(42)] = 1258,
  [SMALL_STATE(43)] = 1277,
  [SMALL_STATE(44)] = 1296,
  [SMALL_STATE(45)] = 1315,
  [SMALL_STATE(46)] = 1334,
  [SMALL_STATE(47)] = 1353,
  [SMALL_STATE(48)] = 1372,
  [SMALL_STATE(49)] = 1391,
  [SMALL_STATE(50)] = 1410,
  [SMALL_STATE(51)] = 1431,
  [SMALL_STATE(52)] = 1450,
  [SMALL_STATE(53)] = 1469,
  [SMALL_STATE(54)] = 1485,
  [SMALL_STATE(55)] = 1501,
  [SMALL_STATE(56)] = 1517,
  [SMALL_STATE(57)] = 1531,
  [SMALL_STATE(58)] = 1547,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_section, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_section, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_section, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_section, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_input_section_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_input_section_repeat1, 2, 0, 0),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_input_section_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [120] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_input_section_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_value, 1, 0, 1),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_value, 1, 0, 1),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_section, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_input_section, 2, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_value, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_value, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_section, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_input_section, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter_section, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_filter_section, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter_section, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_filter_section, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_input_section_repeat1, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_input_section_repeat1, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_content, 1, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipeline, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 1, 0, 0),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_expression_value, 1, 0, 1), SHIFT(17),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_key, 1, 0, 1),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [200] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_key, 1, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_logstash(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "logstash",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
