/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 54
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 1
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_input = 1,
  anon_sym_filter = 2,
  anon_sym_output = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_EQ_GT = 6,
  aux_sym_whitespace_token1 = 7,
  anon_sym_POUND = 8,
  aux_sym_comment_token1 = 9,
  sym_string = 10,
  sym_plugin_name = 11,
  sym_number = 12,
  sym_boolean = 13,
  anon_sym_LBRACK = 14,
  anon_sym_COMMA = 15,
  anon_sym_RBRACK = 16,
  sym_source_file = 17,
  sym_pipeline = 18,
  sym_input_section = 19,
  sym_filter_section = 20,
  sym_output_section = 21,
  sym_block = 22,
  sym_block_content = 23,
  sym_expression = 24,
  sym_expression_key = 25,
  sym_expression_value = 26,
  sym_whitespace = 27,
  sym_comment = 28,
  sym_array = 29,
  aux_sym_source_file_repeat1 = 30,
  aux_sym_input_section_repeat1 = 31,
  aux_sym_block_repeat1 = 32,
  aux_sym_array_repeat1 = 33,
  anon_alias_sym_identifier = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_input] = "input",
  [anon_sym_filter] = "filter",
  [anon_sym_output] = "output",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ_GT] = "=>",
  [aux_sym_whitespace_token1] = "whitespace_token1",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_string] = "string",
  [sym_plugin_name] = "plugin_name",
  [sym_number] = "number",
  [sym_boolean] = "boolean",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym_pipeline] = "pipeline",
  [sym_input_section] = "input_section",
  [sym_filter_section] = "filter_section",
  [sym_output_section] = "output_section",
  [sym_block] = "block",
  [sym_block_content] = "block_content",
  [sym_expression] = "expression",
  [sym_expression_key] = "expression_key",
  [sym_expression_value] = "expression_value",
  [sym_whitespace] = "whitespace",
  [sym_comment] = "comment",
  [sym_array] = "array",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_input_section_repeat1] = "input_section_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [anon_alias_sym_identifier] = "identifier",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_input] = anon_sym_input,
  [anon_sym_filter] = anon_sym_filter,
  [anon_sym_output] = anon_sym_output,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [aux_sym_whitespace_token1] = aux_sym_whitespace_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_string] = sym_string,
  [sym_plugin_name] = sym_plugin_name,
  [sym_number] = sym_number,
  [sym_boolean] = sym_boolean,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym_pipeline] = sym_pipeline,
  [sym_input_section] = sym_input_section,
  [sym_filter_section] = sym_filter_section,
  [sym_output_section] = sym_output_section,
  [sym_block] = sym_block,
  [sym_block_content] = sym_block_content,
  [sym_expression] = sym_expression,
  [sym_expression_key] = sym_expression_key,
  [sym_expression_value] = sym_expression_value,
  [sym_whitespace] = sym_whitespace,
  [sym_comment] = sym_comment,
  [sym_array] = sym_array,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_input_section_repeat1] = aux_sym_input_section_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [anon_alias_sym_identifier] = anon_alias_sym_identifier,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_input] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_filter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_output] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_whitespace_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_plugin_name] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_pipeline] = {
    .visible = true,
    .named = true,
  },
  [sym_input_section] = {
    .visible = true,
    .named = true,
  },
  [sym_filter_section] = {
    .visible = true,
    .named = true,
  },
  [sym_output_section] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block_content] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_key] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_value] = {
    .visible = true,
    .named = true,
  },
  [sym_whitespace] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_input_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_identifier] = {
    .visible = true,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = anon_alias_sym_identifier,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 6,
  [17] = 2,
  [18] = 4,
  [19] = 8,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 32,
  [42] = 42,
  [43] = 30,
  [44] = 31,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '"', 2,
        '#', 33,
        ',', 62,
        '=', 3,
        '[', 61,
        ']', 63,
        'f', 38,
        'i', 44,
        'o', 54,
        't', 48,
        '{', 28,
        '}', 29,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        '#', 33,
        ',', 62,
        '[', 61,
        ']', 63,
        'f', 39,
        't', 48,
        '{', 28,
        '}', 29,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(37);
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(30);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'i') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == 'p') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(4);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 19:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == 'f') ADVANCE(5);
      if (lookahead == 'i') ADVANCE(7);
      if (lookahead == 'o') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_input);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_input);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_filter);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_filter);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_output);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_output);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_whitespace_token1);
      if (lookahead == '\n') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_whitespace_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '#') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'a') ADVANCE(42);
      if (lookahead == 'i') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'a') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'e') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'e') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'l') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'l') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'n') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'p') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'p') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'r') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'r') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 's') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 't') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 't') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 't') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 't') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'u') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'u') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'u') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'u') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_plugin_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 20},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 20},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 20},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 20},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 20},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 35},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {(TSStateId)(-1),},
  [53] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_whitespace] = STATE(0),
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_input] = ACTIONS(1),
    [anon_sym_filter] = ACTIONS(1),
    [anon_sym_output] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [aux_sym_whitespace_token1] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(5),
    [sym_string] = ACTIONS(1),
    [sym_plugin_name] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(48),
    [sym_pipeline] = STATE(34),
    [sym_input_section] = STATE(36),
    [sym_filter_section] = STATE(36),
    [sym_output_section] = STATE(36),
    [sym_whitespace] = STATE(1),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_input] = ACTIONS(9),
    [anon_sym_filter] = ACTIONS(11),
    [anon_sym_output] = ACTIONS(13),
    [aux_sym_whitespace_token1] = ACTIONS(3),
    [anon_sym_POUND] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(21), 1,
      sym_plugin_name,
    STATE(12), 1,
      aux_sym_block_repeat1,
    STATE(39), 1,
      sym_block,
    STATE(40), 1,
      sym_block_content,
    STATE(42), 1,
      sym_expression,
    STATE(49), 1,
      sym_expression_key,
    STATE(2), 2,
      sym_whitespace,
      sym_comment,
  [38] = 9,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_input,
    ACTIONS(28), 1,
      anon_sym_filter,
    ACTIONS(31), 1,
      anon_sym_output,
    STATE(34), 1,
      sym_pipeline,
    STATE(3), 3,
      sym_whitespace,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(36), 3,
      sym_input_section,
      sym_filter_section,
      sym_output_section,
  [70] = 12,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(21), 1,
      sym_plugin_name,
    STATE(8), 1,
      aux_sym_block_repeat1,
    STATE(39), 1,
      sym_block,
    STATE(40), 1,
      sym_block_content,
    STATE(42), 1,
      sym_expression,
    STATE(49), 1,
      sym_expression_key,
    STATE(4), 2,
      sym_whitespace,
      sym_comment,
  [108] = 10,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_input,
    ACTIONS(11), 1,
      anon_sym_filter,
    ACTIONS(13), 1,
      anon_sym_output,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(34), 1,
      sym_pipeline,
    STATE(5), 2,
      sym_whitespace,
      sym_comment,
    STATE(36), 3,
      sym_input_section,
      sym_filter_section,
      sym_output_section,
  [142] = 12,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(21), 1,
      sym_plugin_name,
    ACTIONS(36), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      aux_sym_block_repeat1,
    STATE(39), 1,
      sym_block,
    STATE(40), 1,
      sym_block_content,
    STATE(42), 1,
      sym_expression,
    STATE(49), 1,
      sym_expression_key,
    STATE(6), 2,
      sym_whitespace,
      sym_comment,
  [180] = 11,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(40), 1,
      sym_plugin_name,
    ACTIONS(42), 1,
      sym_boolean,
    ACTIONS(44), 1,
      anon_sym_LBRACK,
    STATE(9), 1,
      sym_array,
    STATE(35), 1,
      sym_expression_value,
    STATE(38), 1,
      sym_block,
    ACTIONS(38), 2,
      sym_string,
      sym_number,
    STATE(7), 2,
      sym_whitespace,
      sym_comment,
  [216] = 12,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(21), 1,
      sym_plugin_name,
    ACTIONS(46), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      aux_sym_block_repeat1,
    STATE(39), 1,
      sym_block,
    STATE(40), 1,
      sym_block_content,
    STATE(42), 1,
      sym_expression,
    STATE(49), 1,
      sym_expression_key,
    STATE(8), 2,
      sym_whitespace,
      sym_comment,
  [254] = 5,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(50), 1,
      sym_boolean,
    STATE(9), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(48), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
      sym_plugin_name,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [278] = 11,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(42), 1,
      sym_boolean,
    ACTIONS(44), 1,
      anon_sym_LBRACK,
    ACTIONS(52), 1,
      sym_plugin_name,
    ACTIONS(54), 1,
      anon_sym_RBRACK,
    STATE(9), 1,
      sym_array,
    STATE(13), 1,
      aux_sym_array_repeat1,
    STATE(27), 1,
      sym_expression_value,
    ACTIONS(38), 2,
      sym_string,
      sym_number,
    STATE(10), 2,
      sym_whitespace,
      sym_comment,
  [314] = 5,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(58), 1,
      sym_boolean,
    STATE(11), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(56), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
      sym_plugin_name,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [338] = 11,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(60), 1,
      anon_sym_LBRACE,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    ACTIONS(65), 1,
      sym_string,
    ACTIONS(68), 1,
      sym_plugin_name,
    STATE(39), 1,
      sym_block,
    STATE(40), 1,
      sym_block_content,
    STATE(42), 1,
      sym_expression,
    STATE(49), 1,
      sym_expression_key,
    STATE(12), 3,
      sym_whitespace,
      sym_comment,
      aux_sym_block_repeat1,
  [374] = 11,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(42), 1,
      sym_boolean,
    ACTIONS(44), 1,
      anon_sym_LBRACK,
    ACTIONS(52), 1,
      sym_plugin_name,
    ACTIONS(71), 1,
      anon_sym_RBRACK,
    STATE(9), 1,
      sym_array,
    STATE(15), 1,
      aux_sym_array_repeat1,
    STATE(27), 1,
      sym_expression_value,
    ACTIONS(38), 2,
      sym_string,
      sym_number,
    STATE(13), 2,
      sym_whitespace,
      sym_comment,
  [410] = 5,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(75), 1,
      sym_boolean,
    STATE(14), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(73), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
      sym_plugin_name,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [434] = 10,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(80), 1,
      sym_plugin_name,
    ACTIONS(83), 1,
      sym_boolean,
    ACTIONS(86), 1,
      anon_sym_LBRACK,
    ACTIONS(89), 1,
      anon_sym_RBRACK,
    STATE(9), 1,
      sym_array,
    STATE(27), 1,
      sym_expression_value,
    ACTIONS(77), 2,
      sym_string,
      sym_number,
    STATE(15), 3,
      sym_whitespace,
      sym_comment,
      aux_sym_array_repeat1,
  [468] = 12,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(21), 1,
      sym_plugin_name,
    ACTIONS(91), 1,
      anon_sym_RBRACE,
    STATE(17), 1,
      aux_sym_block_repeat1,
    STATE(39), 1,
      sym_block,
    STATE(40), 1,
      sym_block_content,
    STATE(42), 1,
      sym_expression,
    STATE(49), 1,
      sym_expression_key,
    STATE(16), 2,
      sym_whitespace,
      sym_comment,
  [506] = 12,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(21), 1,
      sym_plugin_name,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      aux_sym_block_repeat1,
    STATE(39), 1,
      sym_block,
    STATE(40), 1,
      sym_block_content,
    STATE(42), 1,
      sym_expression,
    STATE(49), 1,
      sym_expression_key,
    STATE(17), 2,
      sym_whitespace,
      sym_comment,
  [544] = 12,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(21), 1,
      sym_plugin_name,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    STATE(19), 1,
      aux_sym_block_repeat1,
    STATE(39), 1,
      sym_block,
    STATE(40), 1,
      sym_block_content,
    STATE(42), 1,
      sym_expression,
    STATE(49), 1,
      sym_expression_key,
    STATE(18), 2,
      sym_whitespace,
      sym_comment,
  [582] = 12,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      sym_string,
    ACTIONS(21), 1,
      sym_plugin_name,
    ACTIONS(95), 1,
      anon_sym_RBRACE,
    STATE(12), 1,
      aux_sym_block_repeat1,
    STATE(39), 1,
      sym_block,
    STATE(40), 1,
      sym_block_content,
    STATE(42), 1,
      sym_expression,
    STATE(49), 1,
      sym_expression_key,
    STATE(19), 2,
      sym_whitespace,
      sym_comment,
  [620] = 9,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 1,
      anon_sym_LBRACE,
    ACTIONS(103), 1,
      sym_plugin_name,
    STATE(26), 1,
      aux_sym_input_section_repeat1,
    STATE(29), 1,
      sym_block,
    STATE(20), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(99), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [651] = 9,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(101), 1,
      anon_sym_LBRACE,
    ACTIONS(103), 1,
      sym_plugin_name,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
    STATE(26), 1,
      aux_sym_input_section_repeat1,
    STATE(29), 1,
      sym_block,
    STATE(21), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(107), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [682] = 9,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(101), 1,
      anon_sym_LBRACE,
    ACTIONS(103), 1,
      sym_plugin_name,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      aux_sym_input_section_repeat1,
    STATE(29), 1,
      sym_block,
    STATE(22), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(111), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [713] = 9,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(101), 1,
      anon_sym_LBRACE,
    ACTIONS(103), 1,
      sym_plugin_name,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    STATE(21), 1,
      aux_sym_input_section_repeat1,
    STATE(29), 1,
      sym_block,
    STATE(23), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(115), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [744] = 9,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(101), 1,
      anon_sym_LBRACE,
    ACTIONS(103), 1,
      sym_plugin_name,
    ACTIONS(117), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      aux_sym_input_section_repeat1,
    STATE(29), 1,
      sym_block,
    STATE(24), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(119), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [775] = 9,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(101), 1,
      anon_sym_LBRACE,
    ACTIONS(103), 1,
      sym_plugin_name,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
    STATE(26), 1,
      aux_sym_input_section_repeat1,
    STATE(29), 1,
      sym_block,
    STATE(25), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(123), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [806] = 8,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    ACTIONS(129), 1,
      anon_sym_LBRACE,
    ACTIONS(132), 1,
      sym_plugin_name,
    STATE(29), 1,
      sym_block,
    ACTIONS(127), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
    STATE(26), 3,
      sym_whitespace,
      sym_comment,
      aux_sym_input_section_repeat1,
  [835] = 6,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(137), 1,
      sym_boolean,
    ACTIONS(139), 1,
      anon_sym_COMMA,
    STATE(27), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(135), 5,
      sym_string,
      sym_plugin_name,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [859] = 5,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(143), 1,
      sym_boolean,
    STATE(28), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(141), 6,
      sym_string,
      sym_plugin_name,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [881] = 5,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(145), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    STATE(29), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(147), 4,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
      sym_plugin_name,
  [902] = 5,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(149), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    STATE(30), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(151), 4,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
      sym_plugin_name,
  [923] = 5,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(153), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    STATE(31), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(155), 4,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
      sym_plugin_name,
  [944] = 5,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(157), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    STATE(32), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(159), 4,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
      sym_plugin_name,
  [965] = 5,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(161), 1,
      sym_boolean,
    STATE(33), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(89), 5,
      sym_string,
      sym_plugin_name,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [986] = 4,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    STATE(34), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(163), 4,
      ts_builtin_sym_end,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [1003] = 4,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    STATE(35), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(165), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
      sym_plugin_name,
  [1020] = 4,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    STATE(36), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(167), 4,
      ts_builtin_sym_end,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [1037] = 5,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    STATE(37), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(141), 3,
      anon_sym_RBRACE,
      sym_string,
      sym_plugin_name,
  [1056] = 4,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    STATE(38), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(165), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
      sym_plugin_name,
  [1073] = 4,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    STATE(39), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(172), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
      sym_plugin_name,
  [1090] = 4,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    STATE(40), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(174), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
      sym_plugin_name,
  [1107] = 4,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    STATE(41), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(157), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
      sym_plugin_name,
  [1124] = 4,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    STATE(42), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(172), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
      sym_plugin_name,
  [1141] = 4,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    STATE(43), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(149), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
      sym_plugin_name,
  [1158] = 4,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    STATE(44), 2,
      sym_whitespace,
      sym_comment,
    ACTIONS(153), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_string,
      sym_plugin_name,
  [1175] = 5,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(176), 1,
      anon_sym_LBRACE,
    ACTIONS(178), 1,
      anon_sym_EQ_GT,
    STATE(45), 2,
      sym_whitespace,
      sym_comment,
  [1192] = 4,
    ACTIONS(180), 1,
      aux_sym_whitespace_token1,
    ACTIONS(182), 1,
      anon_sym_POUND,
    ACTIONS(184), 1,
      aux_sym_comment_token1,
    STATE(46), 2,
      sym_whitespace,
      sym_comment,
  [1206] = 4,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(186), 1,
      anon_sym_LBRACE,
    STATE(47), 2,
      sym_whitespace,
      sym_comment,
  [1220] = 4,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(188), 1,
      ts_builtin_sym_end,
    STATE(48), 2,
      sym_whitespace,
      sym_comment,
  [1234] = 4,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(190), 1,
      anon_sym_EQ_GT,
    STATE(49), 2,
      sym_whitespace,
      sym_comment,
  [1248] = 4,
    ACTIONS(3), 1,
      aux_sym_whitespace_token1,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(192), 1,
      anon_sym_EQ_GT,
    STATE(50), 2,
      sym_whitespace,
      sym_comment,
  [1262] = 3,
    ACTIONS(5), 1,
      anon_sym_POUND,
    ACTIONS(194), 1,
      aux_sym_whitespace_token1,
    STATE(51), 2,
      sym_whitespace,
      sym_comment,
  [1273] = 1,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
  [1277] = 1,
    ACTIONS(198), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 38,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 142,
  [SMALL_STATE(7)] = 180,
  [SMALL_STATE(8)] = 216,
  [SMALL_STATE(9)] = 254,
  [SMALL_STATE(10)] = 278,
  [SMALL_STATE(11)] = 314,
  [SMALL_STATE(12)] = 338,
  [SMALL_STATE(13)] = 374,
  [SMALL_STATE(14)] = 410,
  [SMALL_STATE(15)] = 434,
  [SMALL_STATE(16)] = 468,
  [SMALL_STATE(17)] = 506,
  [SMALL_STATE(18)] = 544,
  [SMALL_STATE(19)] = 582,
  [SMALL_STATE(20)] = 620,
  [SMALL_STATE(21)] = 651,
  [SMALL_STATE(22)] = 682,
  [SMALL_STATE(23)] = 713,
  [SMALL_STATE(24)] = 744,
  [SMALL_STATE(25)] = 775,
  [SMALL_STATE(26)] = 806,
  [SMALL_STATE(27)] = 835,
  [SMALL_STATE(28)] = 859,
  [SMALL_STATE(29)] = 881,
  [SMALL_STATE(30)] = 902,
  [SMALL_STATE(31)] = 923,
  [SMALL_STATE(32)] = 944,
  [SMALL_STATE(33)] = 965,
  [SMALL_STATE(34)] = 986,
  [SMALL_STATE(35)] = 1003,
  [SMALL_STATE(36)] = 1020,
  [SMALL_STATE(37)] = 1037,
  [SMALL_STATE(38)] = 1056,
  [SMALL_STATE(39)] = 1073,
  [SMALL_STATE(40)] = 1090,
  [SMALL_STATE(41)] = 1107,
  [SMALL_STATE(42)] = 1124,
  [SMALL_STATE(43)] = 1141,
  [SMALL_STATE(44)] = 1158,
  [SMALL_STATE(45)] = 1175,
  [SMALL_STATE(46)] = 1192,
  [SMALL_STATE(47)] = 1206,
  [SMALL_STATE(48)] = 1220,
  [SMALL_STATE(49)] = 1234,
  [SMALL_STATE(50)] = 1248,
  [SMALL_STATE(51)] = 1262,
  [SMALL_STATE(52)] = 1273,
  [SMALL_STATE(53)] = 1277,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_value, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_value, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_section, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_input_section, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter_section, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_filter_section, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_section, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_section, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter_section, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_filter_section, 1, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_section, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_input_section, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_section, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_section, 2, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_input_section_repeat1, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_input_section_repeat1, 2, 0, 0),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_input_section_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [132] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_input_section_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_value, 1, 0, 1),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_value, 1, 0, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_input_section_repeat1, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_input_section_repeat1, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipeline, 1, 0, 0),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_expression_value, 1, 0, 1), SHIFT(18),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_content, 1, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 1, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_key, 1, 0, 1),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [188] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_key, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_whitespace, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_logstash(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "logstash",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
