/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 59
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 1
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_input = 1,
  anon_sym_filter = 2,
  anon_sym_output = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_EQ_GT = 6,
  sym_whitespace = 7,
  aux_sym_comment_token1 = 8,
  aux_sym_comment_token2 = 9,
  anon_sym_DQUOTE = 10,
  sym_string_content = 11,
  sym_string_var = 12,
  sym_plugin_name = 13,
  sym_number = 14,
  sym_boolean = 15,
  anon_sym_LBRACK = 16,
  anon_sym_COMMA = 17,
  anon_sym_RBRACK = 18,
  sym_source_file = 19,
  sym_pipeline = 20,
  sym_input_section = 21,
  sym_filter_section = 22,
  sym_output_section = 23,
  sym_block = 24,
  sym_block_content = 25,
  sym_expression = 26,
  sym_expression_key = 27,
  sym_expression_value = 28,
  sym_comment = 29,
  sym_string = 30,
  sym_array = 31,
  aux_sym_source_file_repeat1 = 32,
  aux_sym_input_section_repeat1 = 33,
  aux_sym_block_repeat1 = 34,
  aux_sym_string_repeat1 = 35,
  aux_sym_array_repeat1 = 36,
  anon_alias_sym_identifier = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_input] = "input",
  [anon_sym_filter] = "filter",
  [anon_sym_output] = "output",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ_GT] = "=>",
  [sym_whitespace] = "whitespace",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_content] = "string_content",
  [sym_string_var] = "string_var",
  [sym_plugin_name] = "plugin_name",
  [sym_number] = "number",
  [sym_boolean] = "boolean",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym_pipeline] = "pipeline",
  [sym_input_section] = "input_section",
  [sym_filter_section] = "filter_section",
  [sym_output_section] = "output_section",
  [sym_block] = "block",
  [sym_block_content] = "block_content",
  [sym_expression] = "expression",
  [sym_expression_key] = "expression_key",
  [sym_expression_value] = "expression_value",
  [sym_comment] = "comment",
  [sym_string] = "string",
  [sym_array] = "array",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_input_section_repeat1] = "input_section_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [anon_alias_sym_identifier] = "identifier",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_input] = anon_sym_input,
  [anon_sym_filter] = anon_sym_filter,
  [anon_sym_output] = anon_sym_output,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [sym_whitespace] = sym_whitespace,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_string_var] = sym_string_var,
  [sym_plugin_name] = sym_plugin_name,
  [sym_number] = sym_number,
  [sym_boolean] = sym_boolean,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym_pipeline] = sym_pipeline,
  [sym_input_section] = sym_input_section,
  [sym_filter_section] = sym_filter_section,
  [sym_output_section] = sym_output_section,
  [sym_block] = sym_block,
  [sym_block_content] = sym_block_content,
  [sym_expression] = sym_expression,
  [sym_expression_key] = sym_expression_key,
  [sym_expression_value] = sym_expression_value,
  [sym_comment] = sym_comment,
  [sym_string] = sym_string,
  [sym_array] = sym_array,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_input_section_repeat1] = aux_sym_input_section_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [anon_alias_sym_identifier] = anon_alias_sym_identifier,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_input] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_filter] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_output] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_whitespace] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_string_var] = {
    .visible = true,
    .named = true,
  },
  [sym_plugin_name] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_pipeline] = {
    .visible = true,
    .named = true,
  },
  [sym_input_section] = {
    .visible = true,
    .named = true,
  },
  [sym_filter_section] = {
    .visible = true,
    .named = true,
  },
  [sym_output_section] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block_content] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_key] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_value] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_input_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_identifier] = {
    .visible = true,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = anon_alias_sym_identifier,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 5,
  [12] = 12,
  [13] = 7,
  [14] = 14,
  [15] = 15,
  [16] = 2,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 32,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 31,
  [45] = 35,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '"', 43,
        '#', 37,
        '%', 18,
        ',', 72,
        '=', 3,
        '[', 71,
        ']', 73,
        'f', 48,
        'i', 54,
        'o', 64,
        't', 58,
        '{', 30,
        '}', 31,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 43,
        '#', 37,
        '%', 18,
        ',', 72,
        '=', 3,
        '[', 71,
        ']', 73,
        'f', 49,
        't', 58,
        '{', 30,
        '}', 31,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(43);
      if (lookahead == '#') ADVANCE(45);
      if (lookahead == '%') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'i') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == 'p') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(4);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 18:
      if (lookahead == '{') ADVANCE(21);
      END_STATE();
    case 19:
      if (lookahead == '}') ADVANCE(47);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 21:
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(19);
      END_STATE();
    case 22:
      if (eof) ADVANCE(23);
      if (lookahead == '#') ADVANCE(37);
      if (lookahead == '%') ADVANCE(18);
      if (lookahead == 'f') ADVANCE(5);
      if (lookahead == 'i') ADVANCE(7);
      if (lookahead == 'o') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_input);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_input);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_filter);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_filter);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_output);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_output);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_whitespace);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_whitespace);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\n') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '\n') ADVANCE(33);
      if (lookahead == '#') ADVANCE(36);
      if (lookahead == '%') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead == '}') ADVANCE(42);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '{') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_string_content);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_string_content);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '%' &&
          lookahead != '\\') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '%' &&
          lookahead != '\\') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_string_var);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'a') ADVANCE(52);
      if (lookahead == 'i') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'a') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'e') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'e') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'l') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'l') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'n') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'p') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'p') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'r') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'r') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 's') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 't') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 't') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 't') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 't') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'u') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'u') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'u') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_plugin_name);
      if (lookahead == 'u') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_plugin_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 22},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 22},
  [18] = {.lex_state = 22},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 22},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 22},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 39},
  [57] = {.lex_state = 0},
  [58] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_input] = ACTIONS(1),
    [anon_sym_filter] = ACTIONS(1),
    [anon_sym_output] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [sym_whitespace] = ACTIONS(3),
    [aux_sym_comment_token1] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_string_var] = ACTIONS(3),
    [sym_plugin_name] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(54),
    [sym_pipeline] = STATE(43),
    [sym_input_section] = STATE(46),
    [sym_filter_section] = STATE(46),
    [sym_output_section] = STATE(46),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_input] = ACTIONS(9),
    [anon_sym_filter] = ACTIONS(11),
    [anon_sym_output] = ACTIONS(13),
    [sym_whitespace] = ACTIONS(3),
    [aux_sym_comment_token1] = ACTIONS(5),
    [sym_string_var] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_plugin_name,
    STATE(2), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_block_repeat1,
    STATE(37), 1,
      sym_block,
    STATE(38), 1,
      sym_expression,
    STATE(41), 1,
      sym_block_content,
    STATE(52), 1,
      sym_expression_key,
    STATE(53), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
  [41] = 13,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_plugin_name,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      sym_comment,
    STATE(4), 1,
      aux_sym_block_repeat1,
    STATE(37), 1,
      sym_block,
    STATE(38), 1,
      sym_expression,
    STATE(41), 1,
      sym_block_content,
    STATE(52), 1,
      sym_expression_key,
    STATE(53), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
  [82] = 12,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(28), 1,
      anon_sym_RBRACE,
    ACTIONS(30), 1,
      anon_sym_DQUOTE,
    ACTIONS(33), 1,
      sym_plugin_name,
    STATE(37), 1,
      sym_block,
    STATE(38), 1,
      sym_expression,
    STATE(41), 1,
      sym_block_content,
    STATE(52), 1,
      sym_expression_key,
    STATE(53), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    STATE(4), 2,
      sym_comment,
      aux_sym_block_repeat1,
  [121] = 13,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_plugin_name,
    ACTIONS(36), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_comment,
    STATE(7), 1,
      aux_sym_block_repeat1,
    STATE(37), 1,
      sym_block,
    STATE(38), 1,
      sym_expression,
    STATE(41), 1,
      sym_block_content,
    STATE(52), 1,
      sym_expression_key,
    STATE(53), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
  [162] = 13,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_plugin_name,
    ACTIONS(38), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym_block_repeat1,
    STATE(6), 1,
      sym_comment,
    STATE(37), 1,
      sym_block,
    STATE(38), 1,
      sym_expression,
    STATE(41), 1,
      sym_block_content,
    STATE(52), 1,
      sym_expression_key,
    STATE(53), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
  [203] = 13,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_plugin_name,
    STATE(4), 1,
      aux_sym_block_repeat1,
    STATE(7), 1,
      sym_comment,
    STATE(37), 1,
      sym_block,
    STATE(38), 1,
      sym_expression,
    STATE(41), 1,
      sym_block_content,
    STATE(52), 1,
      sym_expression_key,
    STATE(53), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
  [244] = 5,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(42), 1,
      sym_boolean,
    STATE(8), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(40), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ_GT,
      anon_sym_DQUOTE,
      sym_plugin_name,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [269] = 12,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(44), 1,
      sym_plugin_name,
    ACTIONS(46), 1,
      sym_number,
    ACTIONS(48), 1,
      sym_boolean,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    STATE(9), 1,
      sym_comment,
    STATE(40), 1,
      sym_expression_value,
    STATE(42), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    STATE(20), 2,
      sym_string,
      sym_array,
  [308] = 5,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(54), 1,
      sym_boolean,
    STATE(10), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(52), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ_GT,
      anon_sym_DQUOTE,
      sym_plugin_name,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [333] = 13,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_plugin_name,
    ACTIONS(56), 1,
      anon_sym_RBRACE,
    STATE(11), 1,
      sym_comment,
    STATE(13), 1,
      aux_sym_block_repeat1,
    STATE(37), 1,
      sym_block,
    STATE(38), 1,
      sym_expression,
    STATE(41), 1,
      sym_block_content,
    STATE(52), 1,
      sym_expression_key,
    STATE(53), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
  [374] = 12,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(46), 1,
      sym_number,
    ACTIONS(48), 1,
      sym_boolean,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      sym_plugin_name,
    ACTIONS(60), 1,
      anon_sym_RBRACK,
    STATE(12), 1,
      sym_comment,
    STATE(14), 1,
      aux_sym_array_repeat1,
    STATE(30), 1,
      sym_expression_value,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    STATE(20), 2,
      sym_string,
      sym_array,
  [413] = 13,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_plugin_name,
    ACTIONS(62), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym_block_repeat1,
    STATE(13), 1,
      sym_comment,
    STATE(37), 1,
      sym_block,
    STATE(38), 1,
      sym_expression,
    STATE(41), 1,
      sym_block_content,
    STATE(52), 1,
      sym_expression_key,
    STATE(53), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
  [454] = 12,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(46), 1,
      sym_number,
    ACTIONS(48), 1,
      sym_boolean,
    ACTIONS(50), 1,
      anon_sym_LBRACK,
    ACTIONS(58), 1,
      sym_plugin_name,
    ACTIONS(64), 1,
      anon_sym_RBRACK,
    STATE(14), 1,
      sym_comment,
    STATE(15), 1,
      aux_sym_array_repeat1,
    STATE(30), 1,
      sym_expression_value,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    STATE(20), 2,
      sym_string,
      sym_array,
  [493] = 11,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      sym_plugin_name,
    ACTIONS(72), 1,
      sym_number,
    ACTIONS(75), 1,
      sym_boolean,
    ACTIONS(78), 1,
      anon_sym_LBRACK,
    ACTIONS(81), 1,
      anon_sym_RBRACK,
    STATE(30), 1,
      sym_expression_value,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    STATE(15), 2,
      sym_comment,
      aux_sym_array_repeat1,
    STATE(20), 2,
      sym_string,
      sym_array,
  [530] = 13,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_plugin_name,
    ACTIONS(62), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      aux_sym_block_repeat1,
    STATE(16), 1,
      sym_comment,
    STATE(37), 1,
      sym_block,
    STATE(38), 1,
      sym_expression,
    STATE(41), 1,
      sym_block_content,
    STATE(52), 1,
      sym_expression_key,
    STATE(53), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
  [571] = 10,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_input,
    ACTIONS(11), 1,
      anon_sym_filter,
    ACTIONS(13), 1,
      anon_sym_output,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      sym_comment,
    STATE(18), 1,
      aux_sym_source_file_repeat1,
    STATE(43), 1,
      sym_pipeline,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    STATE(46), 3,
      sym_input_section,
      sym_filter_section,
      sym_output_section,
  [605] = 9,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    ACTIONS(87), 1,
      anon_sym_input,
    ACTIONS(90), 1,
      anon_sym_filter,
    ACTIONS(93), 1,
      anon_sym_output,
    STATE(43), 1,
      sym_pipeline,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    STATE(18), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
    STATE(46), 3,
      sym_input_section,
      sym_filter_section,
      sym_output_section,
  [637] = 5,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(98), 1,
      sym_boolean,
    STATE(19), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(96), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      sym_plugin_name,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [661] = 5,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(102), 1,
      sym_boolean,
    STATE(20), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(100), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      sym_plugin_name,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [685] = 5,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(106), 1,
      sym_boolean,
    STATE(21), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(104), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      sym_plugin_name,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [709] = 9,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 1,
      anon_sym_LBRACE,
    ACTIONS(114), 1,
      sym_plugin_name,
    STATE(22), 1,
      sym_comment,
    STATE(27), 1,
      aux_sym_input_section_repeat1,
    STATE(33), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(110), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [740] = 9,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(112), 1,
      anon_sym_LBRACE,
    ACTIONS(114), 1,
      sym_plugin_name,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
    STATE(23), 1,
      sym_comment,
    STATE(25), 1,
      aux_sym_input_section_repeat1,
    STATE(33), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(118), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [771] = 8,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
    ACTIONS(124), 1,
      anon_sym_LBRACE,
    ACTIONS(127), 1,
      sym_plugin_name,
    STATE(33), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    STATE(24), 2,
      sym_comment,
      aux_sym_input_section_repeat1,
    ACTIONS(122), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [800] = 9,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(112), 1,
      anon_sym_LBRACE,
    ACTIONS(114), 1,
      sym_plugin_name,
    ACTIONS(130), 1,
      ts_builtin_sym_end,
    STATE(24), 1,
      aux_sym_input_section_repeat1,
    STATE(25), 1,
      sym_comment,
    STATE(33), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(132), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [831] = 9,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(112), 1,
      anon_sym_LBRACE,
    ACTIONS(114), 1,
      sym_plugin_name,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
    STATE(26), 1,
      sym_comment,
    STATE(28), 1,
      aux_sym_input_section_repeat1,
    STATE(33), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(136), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [862] = 9,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(112), 1,
      anon_sym_LBRACE,
    ACTIONS(114), 1,
      sym_plugin_name,
    ACTIONS(138), 1,
      ts_builtin_sym_end,
    STATE(24), 1,
      aux_sym_input_section_repeat1,
    STATE(27), 1,
      sym_comment,
    STATE(33), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(140), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [893] = 9,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(112), 1,
      anon_sym_LBRACE,
    ACTIONS(114), 1,
      sym_plugin_name,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
    STATE(24), 1,
      aux_sym_input_section_repeat1,
    STATE(28), 1,
      sym_comment,
    STATE(33), 1,
      sym_block,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(144), 3,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [924] = 5,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(148), 1,
      sym_boolean,
    STATE(29), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(146), 6,
      anon_sym_DQUOTE,
      sym_plugin_name,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [946] = 6,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(152), 1,
      sym_boolean,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(150), 5,
      anon_sym_DQUOTE,
      sym_plugin_name,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [970] = 5,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    STATE(31), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(156), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(158), 4,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
      sym_plugin_name,
  [991] = 5,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    STATE(32), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(160), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(162), 4,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
      sym_plugin_name,
  [1012] = 5,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    STATE(33), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(164), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(166), 4,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
      sym_plugin_name,
  [1033] = 5,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(168), 1,
      sym_boolean,
    STATE(34), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(81), 5,
      anon_sym_DQUOTE,
      sym_plugin_name,
      sym_number,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1054] = 5,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    STATE(35), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(170), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
    ACTIONS(172), 4,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
      sym_plugin_name,
  [1075] = 4,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    STATE(36), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(160), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      sym_plugin_name,
  [1092] = 4,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    STATE(37), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(174), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      sym_plugin_name,
  [1109] = 4,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    STATE(38), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(174), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      sym_plugin_name,
  [1126] = 5,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(176), 1,
      anon_sym_LBRACE,
    STATE(39), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(146), 3,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      sym_plugin_name,
  [1145] = 4,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    STATE(40), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(179), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      sym_plugin_name,
  [1162] = 4,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    STATE(41), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(181), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      sym_plugin_name,
  [1179] = 4,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    STATE(42), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(179), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      sym_plugin_name,
  [1196] = 4,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    STATE(43), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(183), 4,
      ts_builtin_sym_end,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [1213] = 4,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    STATE(44), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(156), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      sym_plugin_name,
  [1230] = 4,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    STATE(45), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(170), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
      sym_plugin_name,
  [1247] = 4,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    STATE(46), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
    ACTIONS(185), 4,
      ts_builtin_sym_end,
      anon_sym_input,
      anon_sym_filter,
      anon_sym_output,
  [1264] = 5,
    ACTIONS(187), 1,
      sym_whitespace,
    ACTIONS(189), 1,
      aux_sym_comment_token1,
    ACTIONS(191), 1,
      anon_sym_DQUOTE,
    ACTIONS(193), 2,
      sym_string_content,
      sym_string_var,
    STATE(47), 2,
      sym_comment,
      aux_sym_string_repeat1,
  [1282] = 6,
    ACTIONS(187), 1,
      sym_whitespace,
    ACTIONS(189), 1,
      aux_sym_comment_token1,
    ACTIONS(196), 1,
      anon_sym_DQUOTE,
    STATE(47), 1,
      aux_sym_string_repeat1,
    STATE(48), 1,
      sym_comment,
    ACTIONS(198), 2,
      sym_string_content,
      sym_string_var,
  [1302] = 6,
    ACTIONS(187), 1,
      sym_whitespace,
    ACTIONS(189), 1,
      aux_sym_comment_token1,
    ACTIONS(200), 1,
      anon_sym_DQUOTE,
    STATE(48), 1,
      aux_sym_string_repeat1,
    STATE(49), 1,
      sym_comment,
    ACTIONS(198), 2,
      sym_string_content,
      sym_string_var,
  [1322] = 5,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(202), 1,
      anon_sym_LBRACE,
    ACTIONS(204), 1,
      anon_sym_EQ_GT,
    STATE(50), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
  [1339] = 4,
    ACTIONS(187), 1,
      sym_whitespace,
    ACTIONS(189), 1,
      aux_sym_comment_token1,
    STATE(51), 1,
      sym_comment,
    ACTIONS(206), 3,
      anon_sym_DQUOTE,
      sym_string_content,
      sym_string_var,
  [1354] = 4,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(208), 1,
      anon_sym_EQ_GT,
    STATE(52), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
  [1368] = 4,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(210), 1,
      anon_sym_EQ_GT,
    STATE(53), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
  [1382] = 4,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(212), 1,
      ts_builtin_sym_end,
    STATE(54), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
  [1396] = 4,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(214), 1,
      anon_sym_LBRACE,
    STATE(55), 1,
      sym_comment,
    ACTIONS(3), 2,
      sym_whitespace,
      sym_string_var,
  [1410] = 4,
    ACTIONS(189), 1,
      aux_sym_comment_token1,
    ACTIONS(216), 1,
      aux_sym_comment_token2,
    STATE(56), 1,
      sym_comment,
    ACTIONS(187), 2,
      sym_whitespace,
      sym_string_var,
  [1424] = 4,
    ACTIONS(3), 1,
      sym_string_var,
    ACTIONS(5), 1,
      aux_sym_comment_token1,
    ACTIONS(218), 1,
      sym_whitespace,
    STATE(57), 1,
      sym_comment,
  [1437] = 1,
    ACTIONS(220), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 41,
  [SMALL_STATE(4)] = 82,
  [SMALL_STATE(5)] = 121,
  [SMALL_STATE(6)] = 162,
  [SMALL_STATE(7)] = 203,
  [SMALL_STATE(8)] = 244,
  [SMALL_STATE(9)] = 269,
  [SMALL_STATE(10)] = 308,
  [SMALL_STATE(11)] = 333,
  [SMALL_STATE(12)] = 374,
  [SMALL_STATE(13)] = 413,
  [SMALL_STATE(14)] = 454,
  [SMALL_STATE(15)] = 493,
  [SMALL_STATE(16)] = 530,
  [SMALL_STATE(17)] = 571,
  [SMALL_STATE(18)] = 605,
  [SMALL_STATE(19)] = 637,
  [SMALL_STATE(20)] = 661,
  [SMALL_STATE(21)] = 685,
  [SMALL_STATE(22)] = 709,
  [SMALL_STATE(23)] = 740,
  [SMALL_STATE(24)] = 771,
  [SMALL_STATE(25)] = 800,
  [SMALL_STATE(26)] = 831,
  [SMALL_STATE(27)] = 862,
  [SMALL_STATE(28)] = 893,
  [SMALL_STATE(29)] = 924,
  [SMALL_STATE(30)] = 946,
  [SMALL_STATE(31)] = 970,
  [SMALL_STATE(32)] = 991,
  [SMALL_STATE(33)] = 1012,
  [SMALL_STATE(34)] = 1033,
  [SMALL_STATE(35)] = 1054,
  [SMALL_STATE(36)] = 1075,
  [SMALL_STATE(37)] = 1092,
  [SMALL_STATE(38)] = 1109,
  [SMALL_STATE(39)] = 1126,
  [SMALL_STATE(40)] = 1145,
  [SMALL_STATE(41)] = 1162,
  [SMALL_STATE(42)] = 1179,
  [SMALL_STATE(43)] = 1196,
  [SMALL_STATE(44)] = 1213,
  [SMALL_STATE(45)] = 1230,
  [SMALL_STATE(46)] = 1247,
  [SMALL_STATE(47)] = 1264,
  [SMALL_STATE(48)] = 1282,
  [SMALL_STATE(49)] = 1302,
  [SMALL_STATE(50)] = 1322,
  [SMALL_STATE(51)] = 1339,
  [SMALL_STATE(52)] = 1354,
  [SMALL_STATE(53)] = 1368,
  [SMALL_STATE(54)] = 1382,
  [SMALL_STATE(55)] = 1396,
  [SMALL_STATE(56)] = 1410,
  [SMALL_STATE(57)] = 1424,
  [SMALL_STATE(58)] = 1437,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_value, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_value, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_section, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_input_section, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_section, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_section, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_input_section_repeat1, 2, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_input_section_repeat1, 2, 0, 0),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_input_section_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [127] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_input_section_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_section, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_section, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter_section, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_filter_section, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_input_section, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_input_section, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filter_section, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_filter_section, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_value, 1, 0, 1),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_value, 1, 0, 1),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_input_section_repeat1, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_input_section_repeat1, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_content, 1, 0, 0),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_expression_value, 1, 0, 1), SHIFT(16),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 1, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipeline, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_key, 1, 0, 1),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 1, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_key, 1, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_logstash(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "logstash",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
